// Mirrors supabase/functions/_shared/allowedValues.ts. Duplicated rather than imported
// across the Metro (RN) / Deno (edge functions) boundary — the two runtimes don't share a
// module graph. Keep both lists in sync if the taxonomy changes.

export const ROLE_CATEGORIES = [
  'founder', 'investor', 'operator', 'engineer', 'designer', 'researcher', 'student', 'strategist',
] as const;

export const SENIORITY_BANDS = ['early', 'mid', 'senior', 'executive'] as const;

export const INDUSTRIES = [
  'fintech', 'finance', 'investments', 'vcpe', 'venture capital', 'private equity',
  'public equity', 'banking', 'insurance', 'insurtech', 'accounting',
  'consulting', 'legal tech', 'law', 'foodtech', 'food beverage', 'agriculture', 'climate',
  'energy', 'renewable energy', 'oil gas', 'mining', 'utilities', 'water', 'waste management',
  'healthtech', 'pharma', 'biotech', 'medical devices', 'healthcare services',
  'wellness fitness', 'logistics', 'transportation', 'shipping', 'aviation', 'automotive',
  'aerospace defense', 'space', 'manufacturing', 'semiconductors', 'hardware', 'robotics',
  'iot', 'consumer', 'retail', 'e-commerce', 'luxury goods', 'beauty cosmetics', 'fashion',
  'enterprise', 'software', 'cloud computing', 'data analytics', 'ai infrastructure',
  'cybersecurity', 'web3', 'gaming', 'esports', 'media', 'entertainment', 'music', 'film',
  'publishing', 'journalism', 'advertising', 'marketing tech', 'public relations',
  'market research', 'edtech', 'education', 'childcare', 'proptech', 'real estate',
  'construction', 'architecture', 'interior design', 'travel', 'hospitality', 'hr tech',
  'staffing recruiting', 'government', 'nonprofit', 'social impact', 'mobility',
  'telecommunications', 'security services', 'environmental services', 'veterinary pet care',
  'senior care', 'sports',
] as const;

export type RoleCategory = (typeof ROLE_CATEGORIES)[number];
export type SeniorityBand = (typeof SENIORITY_BANDS)[number];
export type Industry = (typeof INDUSTRIES)[number];

export const ROLE_CATEGORY_LABELS: Record<RoleCategory, string> = {
  founder: 'Founder',
  investor: 'Investor',
  operator: 'Operator',
  engineer: 'Engineer',
  designer: 'Designer',
  researcher: 'Researcher',
  student: 'Student',
  strategist: 'Strategist',
};

export const SENIORITY_BAND_LABELS: Record<SeniorityBand, string> = {
  early: 'Early career',
  mid: 'Mid level',
  senior: 'Senior',
  executive: 'Executive',
};

export const INDUSTRY_LABELS: Record<Industry, string> = {
  fintech: 'Fintech',
  finance: 'Finance',
  investments: 'Investments',
  vcpe: 'VCPE',
  'venture capital': 'Venture Capital',
  'private equity': 'Private Equity',
  'public equity': 'Public Equity',
  banking: 'Banking',
  insurance: 'Insurance',
  insurtech: 'Insurtech',
  accounting: 'Accounting',
  consulting: 'Consulting',
  'legal tech': 'Legal Tech',
  law: 'Law',
  foodtech: 'Foodtech',
  'food beverage': 'Food & Beverage',
  agriculture: 'Agriculture',
  climate: 'Climate',
  energy: 'Energy',
  'renewable energy': 'Renewable Energy',
  'oil gas': 'Oil & Gas',
  mining: 'Mining',
  utilities: 'Utilities',
  water: 'Water',
  'waste management': 'Waste Management',
  healthtech: 'Healthtech',
  pharma: 'Pharma',
  biotech: 'Biotech',
  'medical devices': 'Medical Devices',
  'healthcare services': 'Healthcare Services',
  'wellness fitness': 'Wellness & Fitness',
  logistics: 'Logistics',
  transportation: 'Transportation',
  shipping: 'Shipping',
  aviation: 'Aviation',
  automotive: 'Automotive',
  'aerospace defense': 'Aerospace & Defense',
  space: 'Space',
  manufacturing: 'Manufacturing',
  semiconductors: 'Semiconductors',
  hardware: 'Hardware / Deep Tech',
  robotics: 'Robotics',
  iot: 'IoT',
  consumer: 'Consumer',
  retail: 'Retail',
  'e-commerce': 'E-commerce',
  'luxury goods': 'Luxury Goods',
  'beauty cosmetics': 'Beauty & Cosmetics',
  fashion: 'Fashion',
  enterprise: 'Enterprise',
  software: 'Software',
  'cloud computing': 'Cloud Computing',
  'data analytics': 'Data & Analytics',
  'ai infrastructure': 'AI / ML Infrastructure',
  cybersecurity: 'Cybersecurity',
  web3: 'Web3 / Crypto',
  gaming: 'Gaming',
  esports: 'Esports',
  media: 'Media',
  entertainment: 'Entertainment',
  music: 'Music',
  film: 'Film & TV',
  publishing: 'Publishing',
  journalism: 'Journalism',
  advertising: 'Advertising',
  'marketing tech': 'Marketing Tech',
  'public relations': 'Public Relations',
  'market research': 'Market Research',
  edtech: 'Edtech',
  education: 'Education',
  childcare: 'Childcare',
  proptech: 'Proptech',
  'real estate': 'Real Estate',
  construction: 'Construction',
  architecture: 'Architecture',
  'interior design': 'Interior Design',
  travel: 'Travel',
  hospitality: 'Hospitality',
  'hr tech': 'HR Tech',
  'staffing recruiting': 'Staffing & Recruiting',
  government: 'Government',
  nonprofit: 'Nonprofit',
  'social impact': 'Social Impact',
  mobility: 'Mobility & Transportation',
  telecommunications: 'Telecommunications',
  'security services': 'Security Services',
  'environmental services': 'Environmental Services',
  'veterinary pet care': 'Veterinary & Pet Care',
  'senior care': 'Senior Care',
  sports: 'Sports',
};
